<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Faker\Factory as Faker;
use App\Models\Category;
use App\Models\Product;
use App\Models\AttributeValue;
use App\Models\ProductAttribute;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $dataProduct = [
            'cake' => [
                'Bánh Mỳ Bơ Tỏi' => 'Bánh mì bơ tỏi là món ăn vặt siêu ngon mà bạn không thể bỏ qua! Với lớp bánh mì giòn tan và thơm phức bơ tỏi nướng vàng rụm, món này sẽ chinh phục mọi tín đồ ẩm thực. Mỗi miếng bánh mang đến vị bơ béo ngậy, hòa quyện hoàn hảo với hương thơm của tỏi nướng. Chỉ cần một miếng là bạn đã muốn ăn thêm ngay! Thích hợp để nhâm nhi cùng bạn bè hay thưởng thức khi xem phim. Đặc biệt, món này còn là lựa chọn tuyệt vời cho những buổi tiệc nhỏ. Bánh mì bơ tỏi chắc chắn sẽ khiến bạn mê mẩn ngay từ lần đầu tiên!',
                'Bánh Phô Mai Việt Quất' => 'Bánh phô mai việt quất là một món ngọt cực kỳ hấp dẫn mà bạn không thể bỏ lỡ! Với lớp vỏ bánh mềm mịn, bên trong là nhân phô mai béo ngậy, hòa quyện cùng vị chua ngọt của việt quất tươi ngon, món này sẽ làm bạn tan chảy ngay từ miếng đầu tiên. Hương vị thơm lừng của phô mai kết hợp với vị chua dịu của việt quất tạo nên trải nghiệm tuyệt vời cho vị giác. Rất thích hợp để thưởng thức trong những buổi trà chiều hoặc làm món ăn vặt giữa ngày. Hãy chia sẻ với bạn bè và cảm nhận niềm vui khi cùng nhau thưởng thức món bánh này! Bánh phô mai việt quất chắc chắn sẽ trở thành món yêu thích trong danh sách của bạn!',
                'Bánh Sừng Bò Bơ Nguyên Chất' => 'Bánh sừng bò bơ nguyên chất là món ăn không thể chối từ cho những tín đồ yêu thích sự thơm ngon và béo ngậy! Với lớp vỏ bánh vàng giòn, được làm từ bơ nguyên chất, mỗi miếng bánh đều mang đến cảm giác tan chảy ngay trên đầu lưỡi. Hương bơ tự nhiên lan tỏa, quyện cùng độ giòn rụm tạo nên trải nghiệm tuyệt vời cho bữa sáng hoặc bữa xế. Chỉ cần cắn một miếng, bạn sẽ cảm nhận ngay sự mềm mại bên trong và hương vị thơm ngon không thể quên. Hãy cùng bạn bè hoặc gia đình thưởng thức bánh sừng bò bơ nguyên chất và tận hưởng những khoảnh khắc tuyệt vời bên nhau! Chắc chắn món này sẽ khiến bạn phải quay lại lần nữa!',
                'Bánh Sừng Bò Chocolate' => 'Bánh sừng bò chocolate là sự kết hợp hoàn hảo giữa lớp vỏ bánh giòn rụm và nhân chocolate ngọt ngào, làm tan chảy trái tim của mọi tín đồ mê ngọt! Mỗi miếng bánh mang đến một trải nghiệm vị giác tuyệt vời với hương thơm nức mũi và vị chocolate béo ngậy. Bánh được nướng đến độ vàng ruộm, giòn tan ở bên ngoài, còn bên trong là nhân chocolate chảy mềm mại, khiến bạn không thể cưỡng lại được. Thích hợp cho bữa sáng hay một buổi xế nhẹ nhàng, bánh sừng bò chocolate sẽ là lựa chọn hoàn hảo để khởi đầu ngày mới tràn đầy năng lượng. Hãy chia sẻ với bạn bè để cùng nhau thưởng thức những khoảnh khắc ngọt ngào này nhé! Chắc chắn bạn sẽ không muốn bỏ lỡ đâu!',
                'Bánh Sừng Bò Hạnh Nhân' => 'Bánh sừng bò hạnh nhân là món ngon không thể thiếu trong danh sách yêu thích của những tín đồ bánh ngọt! Với lớp vỏ bánh giòn tan, bên trong được nhồi đầy hương vị hạnh nhân thơm lừng, mỗi miếng bánh là một trải nghiệm tuyệt vời cho vị giác. Hạnh nhân được xay nhuyễn hòa quyện cùng đường và bơ, tạo nên sự béo ngậy và ngọt ngào. Khi cắn vào, bạn sẽ cảm nhận được độ giòn bên ngoài và vị bùi bùi bên trong, khiến bạn chỉ muốn ăn thêm mãi không thôi! Thích hợp để thưởng thức cùng tách trà hoặc cà phê, bánh sừng bò hạnh nhân sẽ mang đến cho bạn những giây phút thư giãn tuyệt vời. Đừng quên rủ bạn bè cùng trải nghiệm món bánh thú vị này nhé!',
                'Pain Suisse Thuỵ Sĩ' => 'Pain Suisse Thụy Sĩ là một món bánh ngọt đặc sắc, mang đến hương vị ngọt ngào và độc đáo! Với lớp vỏ bánh mềm mại và phồng xốp, bên trong được nhồi đầy sô-cô-la béo ngậy và những hạt hạnh nhân thơm lừng, mỗi miếng bánh là một hành trình vị giác thú vị. Khi cắn vào, bạn sẽ cảm nhận được sự hòa quyện hoàn hảo giữa vị ngọt của sô-cô-la và độ giòn của hạnh nhân. Món bánh này rất lý tưởng để thưởng thức cùng một tách cà phê sáng hoặc trà chiều, tạo nên một buổi trò chuyện vui vẻ cùng bạn bè. Hãy thử ngay Pain Suisse Thụy Sĩ và để nó làm bừng sáng ngày mới của bạn!',
                'Tart Chocolate' => 'Tart Chocolate là món tráng miệng quyến rũ, hoàn hảo cho những ai yêu thích hương vị sô-cô-la! Với lớp vỏ bánh giòn tan, bên trong là phần nhân sô-cô-la đen mịn màng và béo ngậy, món bánh này sẽ làm bạn say mê ngay từ lần đầu tiên. Một chút đắng nhẹ kết hợp với độ ngọt vừa phải tạo nên trải nghiệm tuyệt vời cho vị giác. Đặc biệt, khi thêm một lớp kem tươi hoặc quả mọng tươi ngon lên trên, món bánh càng trở nên hấp dẫn hơn! Tart Chocolate không chỉ là món ăn, mà còn là niềm vui bất tận cho những buổi tiệc tùng hay các dịp đặc biệt. Đừng quên chia sẻ niềm vui này với bạn bè và gia đình nhé!',
                'Tiramisu' => 'Tiramisu là món tráng miệng nổi tiếng của Ý, khiến bất kỳ ai cũng phải mê mẩn ngay từ lần đầu tiên! Với lớp bánh quy savoiardi ngâm trong cà phê đậm đà, kết hợp với lớp kem mascarpone béo ngậy, mỗi miếng Tiramisu đều mang đến trải nghiệm ngọt ngào và quyến rũ. Hương vị cà phê hòa quyện cùng một chút cacao rắc lên bề mặt tạo nên sự cân bằng hoàn hảo giữa ngọt và đắng. Món bánh này không chỉ tuyệt vời cho những bữa tiệc, mà còn là lựa chọn hoàn hảo để thư giãn sau một ngày dài. Hãy thưởng thức Tiramisu cùng bạn bè và gia đình, và cảm nhận niềm vui trong từng miếng bánh!',
            ],
            'salad' => [
                'Salad Phô Mai Sữa Trâu' => 'Salad Phô Mai Sữa Trâu là sự kết hợp hoàn hảo giữa vị béo ngậy của phô mai sữa trâu và sự tươi mát của rau củ. Món salad này không chỉ ngon miệng mà còn rất bổ dưỡng, thích hợp cho những ngày hè oi ả. Với những miếng phô mai thơm ngon và các loại rau xanh giòn rụm, Salad Phô Mai Sữa Trâu chắc chắn sẽ chinh phục khẩu vị của bạn ngay từ lần đầu thưởng thức!',
                'Salad Phô Mai Sữa Dê' => 'Salad Phô Mai Sữa Dê mang đến một hương vị độc đáo, từ vị chua chua của rau củ hòa quyện với sự béo ngậy của phô mai sữa dê. Món ăn này là sự lựa chọn lý tưởng cho những ai yêu thích sự mới lạ trong bữa ăn hàng ngày. Với màu sắc bắt mắt và hương vị hấp dẫn, Salad Phô Mai Sữa Dê không chỉ là món khai vị mà còn là một trải nghiệm ẩm thực tuyệt vời!',
                'Beetroot Salad' => 'Beetroot Salad nổi bật với sắc đỏ tươi vui và hương vị ngọt ngào của củ dền. Món salad này không chỉ bắt mắt mà còn rất bổ dưỡng, chứa nhiều vitamin và khoáng chất. Kết hợp với các loại rau xanh và gia vị nhẹ nhàng, Beetroot Salad sẽ mang đến cho bạn một bữa ăn lành mạnh và tràn đầy năng lượng. Thưởng thức món salad này, bạn sẽ cảm nhận được sự tươi mới và hứng khởi cho một ngày mới!',
                'Burrata Salad' => 'Burrata Salad là sự kết hợp tuyệt vời giữa phô mai burrata tươi ngon và các loại rau củ tươi mát. Với lớp vỏ ngoài mịn màng và nhân bên trong béo ngậy, phô mai burrata chính là điểm nhấn cho món salad này. Hương vị tươi mát của rau cùng với một chút dầu olive và giấm balsamic tạo nên một bữa ăn thanh nhẹ và đầy sức sống. Hãy thử ngay Burrata Salad để cảm nhận trọn vẹn sự hòa quyện hoàn hảo trong từng miếng ăn!',
            ],
            'pizza' => [
                'Pizza Hải sản Pesto Xanh' => 'Pizza Hải Sản Pesto Xanh là một cuộc phiêu lưu ẩm thực không thể thiếu cho những ai yêu thích hải sản tươi ngon. Mỗi miếng pizza đều được phủ một lớp sốt pesto xanh thơm phức, được làm từ lá húng quế tươi và hạt thông, mang đến hương vị đậm đà và sống động. Không chỉ có vậy, pizza này còn được điểm xuyết bởi những miếng hải sản tươi ngon như tôm, mực và cá hồi, tạo nên một bản giao hưởng tuyệt vời cho vị giác. Với lớp phô mai mozzarella tan chảy ngọt ngào, tất cả hòa quyện lại, đưa bạn đến gần hơn với hương vị biển cả ngay tại bàn ăn. Mỗi miếng pizza không chỉ ngon mà còn mang đến cảm giác phấn khích với những nguyên liệu tươi ngon và bổ dưỡng. Hãy sẵn sàng để khám phá hương vị mới lạ và hấp dẫn này, và cùng nhau tạo ra những khoảnh khắc vui vẻ bên bạn bè và gia đình!',
                'Pizza Chay' => 'Pizza Chay là một món ăn không thể thiếu trong thực đơn cho những tín đồ ăn chay hoặc ai muốn đổi mới khẩu vị. Lớp đế pizza mỏng giòn rụm sẽ làm bạn ngay lập tức say mê, trong khi đó, đầy ắp rau củ tươi ngon như ớt chuông, nấm, hành tây và cà chua tươi mát khiến món ăn này trở nên hấp dẫn hơn bao giờ hết. Đặc biệt, lớp phô mai béo ngậy không chỉ tạo độ mềm mịn mà còn mang lại hương vị phong phú cho mỗi miếng ăn. Món pizza này không chỉ ngon mà còn rất bổ dưỡng, mang lại cho bạn một cảm giác nhẹ nhàng và thanh thoát sau mỗi bữa ăn. Đừng quên thưởng thức Pizza Chay cùng một ly nước trái cây mát lạnh để làm mới vị giác và tận hưởng trọn vẹn hương vị tuyệt vời của món ăn này!',
                'Pizza Carbonara' => 'Pizza Carbonara là một phiên bản độc đáo của món mì carbonara nổi tiếng, đem lại trải nghiệm ẩm thực mới lạ. Với lớp sốt kem béo ngậy, hương vị đậm đà từ trứng và phô mai, pizza này sẽ khiến bạn cảm thấy như đang thưởng thức một bữa tiệc pasta ngay trong từng miếng pizza. Những miếng thịt xông khói thơm lừng được rải đều trên bề mặt, kết hợp với hành tây và hạt tiêu đen, tạo nên một hương vị quyến rũ khó cưỡng. Bên cạnh đó, lớp phô mai mozzarella tan chảy càng làm tăng thêm sự phong phú cho món ăn. Nếu bạn là một tín đồ của ẩm thực Ý, chắc chắn rằng Pizza Carbonara sẽ chinh phục bạn ngay từ miếng đầu tiên. Hãy chuẩn bị sẵn sàng cho một trải nghiệm ẩm thực đầy thú vị và đừng quên chia sẻ với bạn bè!',
                'Pizza Raffaello' => 'Pizza Raffaello là một món ăn đầy sự sáng tạo, mang lại hương vị đặc biệt cho những tín đồ mê pizza. Với lớp đế pizza mỏng giòn rụm và lớp phô mai mozzarella béo ngậy, bạn sẽ ngay lập tức cảm nhận được sự hòa quyện tuyệt vời từ các nguyên liệu tươi ngon. Sốt cà chua tươi mát, cùng với những miếng thịt xông khói, tạo nên một hương vị thơm ngon không thể cưỡng lại. Đặc biệt, món pizza này được trang trí với rau thơm và gia vị độc đáo, khiến cho mỗi miếng ăn đều trở nên thú vị hơn. Pizza Raffaello không chỉ mang lại sự hài lòng cho cái bụng mà còn cho cả tâm hồn bạn. Hãy cùng bạn bè thưởng thức món ăn này và chia sẻ những khoảnh khắc vui vẻ bên nhau!',
                'Pizza Pesto Burrata' => 'Pizza Pesto Burrata là món ăn không thể bỏ qua dành cho những ai yêu thích phô mai và những hương vị độc đáo. Lớp phô mai burrata béo ngậy được đặt ngay giữa pizza, hòa quyện với sốt pesto thơm ngon từ húng quế tươi, mang đến một hương vị đặc biệt không giống ai. Với đế pizza giòn rụm và những lát cà chua chín mọng, mỗi miếng ăn đều là một trải nghiệm nhẹ nhàng và thanh thoát. Sự kết hợp hoàn hảo giữa các nguyên liệu tươi ngon không chỉ làm hài lòng vị giác mà còn khiến bạn cảm thấy thích thú. Đừng quên thưởng thức Pizza Pesto Burrata cùng một ly nước trái cây tươi mát để làm mới vị giác và tận hưởng những khoảnh khắc vui vẻ bên gia đình và bạn bè. Hãy đến và trải nghiệm món pizza này ngay hôm nay!',
                'Pizza Margherita' => 'Pizza Margherita là món pizza cổ điển mà mọi tín đồ ẩm thực không thể bỏ qua! Với đế bánh mỏng giòn rụm, lớp sốt cà chua tươi ngon và phô mai mozzarella tan chảy, đây chính là sự kết hợp hoàn hảo giữa vị béo ngậy và hương vị tươi mát. Không thể thiếu lá húng quế xanh mướt trên bề mặt, thêm chút dầu ô liu thơm ngon, mỗi miếng pizza đều mang đến một trải nghiệm thưởng thức tuyệt vời. Hãy cùng nhau thưởng thức Pizza Margherita trong những buổi tiệc tùng vui vẻ, để cảm nhận hương vị Ý ngay tại nhà mình!',
                'Pizza Burrata Cay' => 'Pizza Burrata Cay là món ăn lý tưởng cho những ai yêu thích sự mới lạ và hương vị cay nồng. Với lớp phô mai burrata mịn màng, hương vị béo ngậy kết hợp hoàn hảo với lớp sốt cà chua cay cay, đây chắc chắn sẽ làm bạn phải mê mẩn ngay từ miếng đầu tiên. Các loại rau củ tươi ngon như ớt chuông và hành tây tạo thêm sắc màu và độ giòn cho món ăn. Đừng quên rắc thêm chút ớt bột để tăng phần kích thích cho vị giác! Pizza Burrata Cay không chỉ là món ăn ngon mà còn mang đến cảm giác phấn khích khi thưởng thức cùng bạn bè và gia đình!',
                'Pizza Cà Tím' => 'Pizza Cà Tím là một lựa chọn thú vị cho những ai yêu thích rau củ. Lớp đế pizza giòn tan được phủ bởi sốt cà chua tươi mát, bên trên là những lát cà tím nướng vàng ươm, hòa quyện cùng phô mai mozzarella tan chảy. Món pizza này không chỉ mang đến hương vị thơm ngon mà còn rất bổ dưỡng, với sự kết hợp hoàn hảo giữa các loại rau củ tươi ngon. Hãy thưởng thức Pizza Cà Tím cùng với một ít húng quế và dầu ô liu, để cảm nhận trọn vẹn hương vị của nó! Đây là món ăn lý tưởng cho những buổi họp mặt hay tiệc tùng đầy vui vẻ!',
                'Pizza Gập Calzone' => 'Pizza Gập Calzone là món pizza độc đáo, mang đến một trải nghiệm hoàn toàn mới lạ cho những tín đồ ẩm thực. Được gập lại như một chiếc túi, món pizza này được nhồi đầy ắp các loại nhân thơm ngon từ phô mai, thịt, đến rau củ tươi mát. Khi cắn vào, bạn sẽ cảm nhận được sự hòa quyện giữa hương vị béo ngậy và tươi mát, tạo nên một cảm giác vô cùng thú vị. Đừng quên thưởng thức Pizza Gập Calzone cùng với một chén sốt cà chua để tăng thêm độ ngon miệng! Hãy cùng nhau khám phá sự thú vị của món ăn này trong những bữa tiệc vui vẻ bên bạn bè!',
                'Pizza 4 Cheese' => 'Pizza 4 Cheese là món pizza hoàn hảo cho những tín đồ yêu thích phô mai! Với sự kết hợp của bốn loại phô mai thơm ngon như mozzarella, cheddar, gorgonzola và parmesan, mỗi miếng pizza đều mang đến một hương vị béo ngậy, quyến rũ và rất đặc trưng. Lớp đế bánh giòn tan sẽ là nền tảng hoàn hảo cho sự hòa quyện này, khiến bạn không thể cưỡng lại. Hãy thưởng thức Pizza 4 Cheese cùng với một chút húng quế tươi và dầu ô liu để tăng thêm phần hấp dẫn! Đây là món ăn lý tưởng để chia sẻ với bạn bè trong những buổi tụ tập hay tiệc tùng đầy vui vẻ!',
                'Pizza Nấm Truffle' => 'Pizza Nấm Truffle là sự kết hợp hoàn hảo giữa hương vị tinh tế và phong cách sang trọng. Với lớp đế bánh giòn rụm, được phủ bởi sốt kem béo ngậy và nấm truffle thơm lừng, món pizza này sẽ chinh phục mọi tín đồ ẩm thực ngay từ miếng đầu tiên. Đặc biệt, các lát phô mai mozzarella tan chảy hòa quyện cùng với hương vị đặc trưng của nấm truffle tạo nên một trải nghiệm ẩm thực đầy mê hoặc. Hãy cùng bạn bè thưởng thức Pizza Nấm Truffle trong những bữa tiệc sang trọng để cảm nhận sự khác biệt và đặc sắc của món ăn này!',
                'Pizza Emilio' => 'Pizza Emilio là một món pizza đậm đà hương vị, đặc biệt thích hợp cho những ai yêu thích sự kết hợp giữa nhiều nguyên liệu khác nhau. Với lớp sốt cà chua tươi ngon, được phủ lên trên là phô mai mozzarella, thịt xông khói, ớt chuông và các loại rau củ tươi, món pizza này sẽ mang đến cho bạn những trải nghiệm vị giác thú vị. Mỗi miếng pizza đều mang đến sự hòa quyện hoàn hảo giữa vị ngọt, chua và béo, khiến bạn không thể cưỡng lại. Hãy mời bạn bè cùng thưởng thức Pizza Emilio trong những buổi họp mặt để thêm phần vui vẻ và thú vị!',
                'Pizza Thịt Ba Chỉ Xông Khói' => 'Pizza Thịt Ba Chỉ Xông Khói là một món ăn đầy quyến rũ, đặc biệt dành cho những tín đồ mê thịt. Với lớp đế bánh giòn tan, được phủ đầy sốt cà chua, phô mai mozzarella và những lát thịt ba chỉ xông khói thơm ngon, mỗi miếng pizza sẽ đưa bạn vào một hành trình ẩm thực thú vị. Hương vị béo ngậy của thịt xông khói kết hợp với sự tươi mát của rau củ sẽ khiến bạn cảm thấy no nê mà vẫn không ngán. Đừng quên thưởng thức Pizza Thịt Ba Chỉ Xông Khói cùng với một chút sốt BBQ để tăng thêm sự hấp dẫn!',
                'Pizza Xúc Xích Đức' => 'Pizza Xúc Xích Đức là món ăn lý tưởng cho những ai yêu thích sự đậm đà và hương vị truyền thống. Với lớp đế bánh giòn rụm, được phủ bởi sốt cà chua tươi ngon và phô mai mozzarella, bên trên là những lát xúc xích Đức thơm phức, món pizza này sẽ khiến bạn mê mẩn ngay từ miếng đầu tiên. Hương vị đặc trưng của xúc xích kết hợp cùng với sự tươi ngon của rau củ sẽ tạo nên một bữa ăn tuyệt vời. Hãy cùng bạn bè thưởng thức Pizza Xúc Xích Đức trong những buổi tiệc tùng để cảm nhận sự vui vẻ và ấm cúng!',
                'Pizza Capricciosa' => 'Pizza Capricciosa là một món ăn hấp dẫn với sự kết hợp hoàn hảo giữa các nguyên liệu phong phú. Lớp đế bánh giòn rụm được phủ bởi sốt cà chua, phô mai mozzarella, nấm, nghệ tây, và cả trái ô liu đen, tạo nên một bữa ăn không thể chối từ. Hương vị đậm đà, cùng với sự tươi mát của rau củ sẽ khiến bạn mê mẩn ngay từ miếng đầu tiên. Đừng quên thưởng thức Pizza Capricciosa cùng với một chén rượu vang để thêm phần hấp dẫn! Đây là món ăn tuyệt vời để chia sẻ cùng gia đình và bạn bè trong những dịp đặc biệt!',
                'Pizza Dăm Bông Parma' => 'Pizza Dăm Bông Parma mang đến cho bạn trải nghiệm ẩm thực đỉnh cao, kết hợp giữa hương vị Ý cổ điển và những nguyên liệu cao cấp nhất. Đế bánh được làm từ bột mì chất lượng, nướng đến độ giòn hoàn hảo, cùng lớp sốt cà chua tươi ngon, ngọt tự nhiên và phô mai mozzarella béo ngậy. Đặc biệt, điểm nhấn của món pizza này chính là những lát dăm bông Parma mỏng tang, được nhập khẩu trực tiếp từ Ý, mang đến vị mặn mà đầy quyến rũ. Để tăng thêm hương vị, một chút húng quế tươi sẽ được rắc lên trên, tạo nên sự hài hòa tuyệt vời giữa các thành phần. Hãy cùng bạn bè tận hưởng Pizza Dăm Bông Parma trong những buổi tiệc tối đầy vui vẻ, để khám phá và chia sẻ hương vị độc đáo, làm cho buổi họp mặt thêm phần thú vị và ấm cúng!',
                'Pizza Napoli Loại 1' => 'Pizza Napoli Loại 1 là một món ăn đặc trưng, mang đến cho bạn cảm giác như đang thưởng thức một bữa ăn tại một quán ăn nhỏ ở Naples. Lớp đế bánh dày, mềm mại được làm từ bột mì tươi, phủ một lớp sốt cà chua tươi ngon và phô mai mozzarella đậm đà. Đặc biệt, pizza này còn được điểm thêm những lát cá cơm mặn mà, cùng với oliu đen và một chút húng quế tươi, mang đến sự kết hợp hoàn hảo giữa các hương vị. Mỗi miếng pizza không chỉ ngon mà còn có sự hòa quyện tuyệt vời giữa vị ngọt, mặn và béo ngậy. Pizza Napoli Loại 1 chính là lựa chọn lý tưởng cho những ai yêu thích sự giản dị nhưng đậm đà của ẩm thực Ý. Hãy thưởng thức món ăn này trong những bữa tiệc hay bữa ăn gia đình để tạo thêm không khí vui vẻ và gắn kết mọi người!',
                'Pizza Napoli Loại 2' => 'Pizza Napoli Loại 2 mang đến một phiên bản đầy sáng tạo của món pizza truyền thống, mang lại sự phong phú trong hương vị và màu sắc. Với lớp đế bánh giòn rụm, được phủ bởi sốt cà chua tươi và phô mai mozzarella thơm ngon, món pizza này còn được thêm vào những lát thịt xông khói đậm đà, nấm tươi và ớt chuông màu sắc, tạo nên sự bắt mắt và hấp dẫn cho mỗi miếng ăn. Hương vị hài hòa giữa vị ngọt, mặn và béo ngậy chắc chắn sẽ khiến bạn không thể cưỡng lại. Pizza Napoli Loại 2 không chỉ là món ăn mà còn là một tác phẩm nghệ thuật trên đĩa, khiến cho bất kỳ bữa tiệc hay bữa ăn nào cũng trở nên đặc biệt hơn. Hãy cùng chia sẻ Pizza Napoli Loại 2 với gia đình và bạn bè để tạo ra những kỷ niệm đáng nhớ và cảm nhận sự vui vẻ trong từng miếng ăn!',
                'Pizza Margherita DOP' => 'Pizza Margherita DOP là biểu tượng của ẩm thực Ý, mang đến sự kết hợp hoàn hảo giữa các nguyên liệu tươi ngon và hương vị truyền thống. Đế bánh mỏng giòn tan được làm từ bột mì chất lượng cao, phủ bởi sốt cà chua San Marzano, nổi tiếng với vị ngọt tự nhiên và đậm đà. Phô mai mozzarella DOP được sử dụng trong món pizza này không chỉ ngon mà còn mang đến độ béo ngậy và kéo sợi hấp dẫn. Một chút húng quế tươi được rắc lên trên, tạo nên sự tươi mới và hương thơm quyến rũ. Mỗi miếng Pizza Margherita DOP không chỉ ngon miệng mà còn mang đậm chất văn hóa ẩm thực Ý, khiến bạn cảm thấy như đang thưởng thức một món ăn tại quê hương của nó. Hãy cùng thưởng thức Pizza Margherita DOP trong những buổi gặp mặt với bạn bè, để cảm nhận sự tinh tế và hồn quê của ẩm thực Ý, và cùng nhau tạo ra những khoảnh khắc vui vẻ và đáng nhớ!',
                'Pizza Pháp' => 'Pizza Pháp là một món ăn đặc sắc mang đậm hương vị tinh tế của ẩm thực Pháp, mang đến cho bạn trải nghiệm ăn uống thú vị. Đế bánh được làm từ bột mì cao cấp, nướng đến mức vàng giòn, cùng lớp sốt cà chua tươi ngon, tạo nên nền tảng tuyệt vời cho các nguyên liệu khác. Món pizza này được phủ đầy phô mai béo ngậy, kết hợp với các loại thảo mộc tươi mát, mang đến sự hài hòa trong mỗi miếng ăn. Thêm vào đó, lớp thịt xông khói thơm phức và các loại rau củ tươi ngon như ớt chuông, hành tây, và nấm, tạo nên sự phong phú về hương vị. Pizza Pháp không chỉ là một món ăn mà còn là một cuộc hành trình khám phá ẩm thực, khiến bạn không thể ngừng thưởng thức và muốn chia sẻ với bạn bè trong những buổi tiệc tùng đầy vui vẻ!',
                'Pizza Nấm Truffle Hảo Hạng' => 'Pizza Nấm Truffle Hảo Hạng là sự lựa chọn hoàn hảo cho những tín đồ yêu thích sự sang trọng và khác biệt. Lớp đế bánh giòn tan, được phủ lớp sốt kem béo ngậy và phô mai mozzarella chất lượng cao, tạo nên sự hài hòa trong hương vị. Nấm truffle thơm lừng được thêm vào, mang đến một vị umami đặc trưng, khiến cho từng miếng pizza trở nên đặc biệt hơn bao giờ hết. Ngoài ra, những lát nấm tươi ngon và một chút húng quế tươi sẽ làm tăng thêm độ tươi mát và hấp dẫn cho món ăn này. Pizza Nấm Truffle Hảo Hạng không chỉ là món ăn cho những buổi tối lãng mạn mà còn là món quà cho bản thân sau những ngày dài. Hãy cùng khám phá và thưởng thức món pizza này với người thân yêu để trải nghiệm hương vị tuyệt vời mà bạn không thể nào quên!',
                'Pizza Marinara' => 'Pizza Marinara mang đậm hương vị biển cả, đưa bạn đến gần hơn với những hải sản tươi ngon từ đại dương. Đế bánh được làm từ bột mì chất lượng cao, nướng giòn rụm và phủ một lớp sốt cà chua tươi ngon, vừa ngọt vừa chua. Điểm nhấn của món pizza này chính là những con tôm, mực, và sò điệp tươi sống, mang đến sự tươi mới và hương vị đặc biệt. Một chút tỏi, dầu ô liu và húng quế tươi được thêm vào, tạo nên sự hòa quyện hoàn hảo giữa các thành phần. Pizza Marinara không chỉ là món ăn ngon mà còn là một trải nghiệm ẩm thực thú vị, đưa bạn đến những buổi tiệc hải sản tuyệt vời. Hãy cùng gia đình và bạn bè thưởng thức Pizza Marinara trong những dịp đặc biệt để cảm nhận sự tươi mát và hương vị tuyệt hảo mà nó mang lại!',
                'Pizza 5 Cheese' => 'Pizza 5 Cheese là một thiên đường cho những ai yêu thích phô mai. Với lớp đế bánh giòn tan được nướng đến hoàn hảo, món pizza này được phủ đầy năm loại phô mai khác nhau, từ mozzarella béo ngậy đến phô mai parmesan, cheddar, gouda và phô mai bleu, tạo nên một sự hòa quyện tuyệt vời của các hương vị. Mỗi miếng ăn đều mang đến một cảm giác béo ngậy và thơm lừng, khiến bạn không thể ngừng lại. Thêm vào đó, một chút húng quế tươi và gia vị sẽ làm nổi bật thêm vị ngon của phô mai, mang đến trải nghiệm ẩm thực đầy thú vị. Pizza 5 Cheese không chỉ là món ăn lý tưởng cho những buổi tụ tập bạn bè mà còn là món quà hoàn hảo cho những ai đam mê ẩm thực. Hãy cùng nhau chia sẻ và thưởng thức món pizza này để cảm nhận sự phong phú và đa dạng của các loại phô mai!',
                'Pizza Sicilian' => 'Pizza Sicilian là món ăn mang đậm phong cách ẩm thực Địa Trung Hải, với đế bánh dày và hình vuông độc đáo. Được phủ lớp sốt cà chua tươi, phô mai mozzarella và những lát thịt xông khói hoặc xúc xích đậm đà, Pizza Sicilian mang đến một trải nghiệm ăn uống thú vị và hấp dẫn. Điểm nhấn của món pizza này chính là sự kết hợp hoàn hảo giữa hương vị của rau củ như ớt chuông, hành tây và olive đen, tạo nên sự phong phú trong từng miếng ăn. Không chỉ ngon miệng, mà Pizza Sicilian còn là món ăn tuyệt vời cho những buổi tiệc tùng, khi bạn muốn chia sẻ với bạn bè và người thân. Hãy cùng nhau thưởng thức Pizza Sicilian trong những khoảnh khắc vui vẻ, để trải nghiệm sự đa dạng và độc đáo của ẩm thực Ý!',
                'Pizza Mật Ong Nóng' => 'Pizza Mật Ong Nóng là món ăn độc đáo kết hợp giữa vị ngọt ngào của mật ong và hương vị mặn mà của phô mai và thịt. Đế bánh được nướng giòn tan, phủ một lớp phô mai mozzarella béo ngậy, và những lát thịt xông khói thơm phức, tạo nên sự hấp dẫn không thể chối từ. Điểm đặc biệt của món pizza này chính là mật ong nóng được rưới lên bề mặt, mang lại một sự kết hợp đầy bất ngờ và thú vị. Mỗi miếng pizza không chỉ ngon mà còn mang đến trải nghiệm độc đáo với sự kết hợp giữa vị ngọt và vị mặn. Pizza Mật Ong Nóng chính là lựa chọn hoàn hảo cho những ai thích khám phá và thử nghiệm những điều mới lạ trong ẩm thực. Hãy cùng thưởng thức món pizza này trong những buổi tiệc hoặc những buổi tối thư giãn, để cảm nhận sự hòa quyện tuyệt vời của các hương vị!',
            ],
            'pasta' => [
                'Pasta Bolognese' => 'Pasta Bolognese là món ăn cổ điển đầy hấp dẫn, mang đến hương vị đậm đà từ nước sốt thịt bằm thơm ngon. Được chế biến từ thịt bò xay nhuyễn, cà chua tươi và một chút rượu vang, sốt Bolognese tạo nên sự hòa quyện tuyệt vời giữa vị ngọt của cà chua và độ béo của thịt. Pasta được nấu vừa tới, mang đến độ dẻo dai hoàn hảo, giúp hấp thụ trọn vẹn hương vị sốt. Món ăn này thường được rắc thêm một ít phô mai parmesan bào mỏng và một chút húng quế tươi để tăng thêm phần hấp dẫn. Pasta Bolognese không chỉ là một món ăn, mà còn là một trải nghiệm ẩm thực tuyệt vời, làm say lòng bất kỳ ai từng thử qua.',
                'Pasta Carbonara' => 'Pasta Carbonara là một trong những món ăn truyền thống nổi tiếng của Ý, nổi bật với hương vị béo ngậy và thơm phức. Món ăn này được làm từ mì spaghetti tươi, kết hợp với một loại sốt đặc biệt từ trứng, phô mai Parmesan và pancetta (thịt xông khói kiểu Ý). Sự kết hợp hoàn hảo giữa trứng và phô mai tạo nên một lớp sốt mịn màng bao phủ từng sợi mì, mang đến trải nghiệm vị giác đầy thú vị. Một chút tiêu đen xay nhuyễn rắc lên trên không chỉ làm tăng hương vị mà còn mang lại màu sắc hấp dẫn cho món ăn. Pasta Carbonara sẽ khiến bạn cảm thấy như đang thưởng thức ẩm thực đích thực tại một quán ăn ven đường ở Rome!',
                'Pasta Xốt Pesto Genovese' => 'Pasta Xốt Pesto Genovese là món ăn không thể bỏ qua cho những ai yêu thích hương vị thơm ngon và tươi mát của húng quế. Sốt pesto được chế biến từ húng quế tươi, hạt thông, tỏi, dầu ô liu và phô mai Parmesan, mang đến một màu xanh tươi mát và hương vị đặc trưng khó quên. Khi kết hợp với mì pasta, sốt pesto không chỉ thấm đẫm vào từng sợi mì mà còn tạo nên một bữa ăn đầy dinh dưỡng và thơm ngon. Món ăn này thường được trang trí bằng một chút húng quế tươi và hạt thông rang để tạo thêm độ giòn và sự hấp dẫn. Pasta Xốt Pesto Genovese là lựa chọn hoàn hảo cho những buổi tối thư giãn, khi bạn muốn thưởng thức một món ăn nhẹ nhàng nhưng vẫn đầy đủ hương vị.',
                'Pasta Xốt Pesto' => 'Pasta Xốt Pesto mang đến một sự kết hợp hoàn hảo giữa hương vị tươi mát của rau củ và sự đậm đà của phô mai. Sốt pesto được làm từ húng quế tươi, hạt thông, tỏi và dầu ô liu, tạo nên một hương vị độc đáo và hấp dẫn. Khi kết hợp với mì pasta, món ăn này không chỉ dễ làm mà còn rất ngon miệng. Từng sợi mì được phủ lớp sốt pesto xanh mướt, khiến mỗi miếng ăn đều tràn ngập hương vị tươi mát. Một chút phô mai Parmesan và tiêu đen xay nhuyễn rắc lên trên, thêm phần hấp dẫn cho món ăn. Pasta Xốt Pesto sẽ là lựa chọn hoàn hảo cho những ai yêu thích ẩm thực Ý và muốn trải nghiệm sự nhẹ nhàng, thanh thoát trong bữa ăn.',
                'Pasta Nấm Hương Shiitake' => 'Pasta Nấm Hương Shiitake là một món ăn thơm ngon và bổ dưỡng, phù hợp cho những ai yêu thích nấm và muốn thưởng thức ẩm thực thực vật. Nấm shiitake được xào với tỏi và dầu ô liu, tạo ra hương thơm hấp dẫn và vị umami đặc trưng. Khi kết hợp với mì pasta tươi, món ăn này không chỉ ngon mà còn rất bổ dưỡng, nhờ vào các chất dinh dưỡng từ nấm. Một chút nước sốt kem mịn màng được thêm vào giúp tạo ra độ béo và làm cho món ăn trở nên hoàn hảo hơn. Pasta Nấm Hương Shiitake là một lựa chọn tuyệt vời cho những buổi tối sum họp, khi bạn muốn mang đến một món ăn vừa ngon vừa tốt cho sức khỏe cho cả gia đình!',
                'Pasta Tôm Cay' => 'Pasta Tôm Cay là món ăn tuyệt vời cho những ai thích hương vị đậm đà và cay nồng. Món pasta này được chế biến từ những con tôm tươi ngon, xào cùng với tỏi, ớt và một chút gia vị đặc trưng, mang đến sự kết hợp hoàn hảo giữa vị ngọt của tôm và độ cay nồng hấp dẫn. Pasta được nấu tới độ al dente, giúp giữ được độ giòn và dẻo, tạo nên trải nghiệm thú vị cho người ăn. Thêm vào đó, một chút rau thơm như húng quế hoặc ngò rí sẽ làm tăng thêm hương vị tươi mát. Pasta Tôm Cay không chỉ là một món ăn mà còn là một cuộc hành trình trải nghiệm ẩm thực đầy kích thích, khiến bạn khó mà quên được!',
            ],
            'soft' => [
                'Coca Classic Lon 320ml' => 'Coca Classic Lon 320ml là thức uống giải khát quen thuộc, mang đến hương vị coca cola nguyên bản mà ai cũng yêu thích. Sảng khoái từng ngụm, giúp xua tan cơn khát và tiếp thêm năng lượng cho ngày dài năng động.',
                'Coca Light Lon 320ml' => 'Coca Light Lon 320ml dành cho những ai yêu thích hương vị truyền thống của coca nhưng muốn giảm bớt lượng đường. Vẫn đậm đà và sảng khoái, nhưng ít calorie hơn, giúp bạn thoải mái thưởng thức mà không lo tăng cân.',
                'Coca Plus Fiber Lon 320ml' => 'Coca Plus Fiber Lon 320ml là lựa chọn mới mẻ cho người thích coca, với bổ sung chất xơ để hỗ trợ tiêu hóa. Không chỉ giúp bạn giải khát, mà còn giúp cảm thấy nhẹ nhàng và tốt cho sức khỏe hơn.',
                'Coca Zero Lon 320ml' => 'Coca Zero Lon 320ml mang đến hương vị coca đậm đà mà không có đường. Hoàn hảo cho những ai muốn thưởng thức vị ngon của coca mà vẫn giữ được chế độ ăn uống lành mạnh.',
                'Fanta Hương Cam Lon 320ml' => 'Fanta Hương Cam Lon 320ml là thức uống ngọt ngào với hương cam thơm mát. Sảng khoái từng ngụm, đem lại cảm giác tươi mới, như đang thưởng thức một ly nước cam tươi mọng vào ngày nắng.',
                'Fanta Hương Nho Lon 320ml' => 'Fanta Hương Nho Lon 320ml mang đến hương vị nho ngọt ngào và thơm lừng. Giải khát cực đã, với từng ngụm đầy sức sống như đang thưởng thức trái nho mọng nước. Đồ uống này sẽ làm bạn mê mẩn ngay từ lần đầu thưởng thức.',
                'Fanta Hương Soda Kem Lon 320ml' => 'Fanta Hương Soda Kem Lon 320ml là sự kết hợp thú vị giữa vị soda sảng khoái và kem ngọt ngào. Vừa uống vừa cảm nhận lớp bọt mịn tan ngay trên đầu lưỡi, mang đến cảm giác vui nhộn như đang thưởng thức ly soda kem lạnh giữa ngày hè nóng bức.',
                'Fanta Hương Xá Xị Lon 320ml' => 'Fanta Hương Xá Xị Lon 320ml là thức uống cổ điển với vị xá xị đậm đà quen thuộc. Hương vị độc đáo và sảng khoái này sẽ gợi nhớ lại những kỷ niệm tuổi thơ, mỗi ngụm đều mang đến sự sảng khoái không thể chối từ.',
                'Fuzetea Trà Bí Đao Lon 320ml' => 'Fuzetea Trà Bí Đao Lon 320ml mang đến hương vị thanh mát của trà bí đao tự nhiên, giúp giải nhiệt và sảng khoái ngay tức thì. Đồ uống này là sự lựa chọn hoàn hảo để thư giãn và làm mới tinh thần sau một ngày dài bận rộn.',
                'Pepsi Nitro Draft Coca Lon 320ml' => 'Pepsi Nitro Draft Coca Lon 320ml là sự sáng tạo mới mẻ từ Pepsi, với lớp bọt nitro mềm mịn và hương vị coca đặc trưng. Cảm giác uống như đang thưởng thức một ly bia tươi nhưng không cồn, mang lại trải nghiệm cực kỳ thú vị.',
                'Pepsi Nitro Draft Vanilla Lon 320ml' => 'Pepsi Nitro Draft Vanilla Lon 320ml kết hợp hương vị coca với chút vani ngọt ngào, tạo ra sự cân bằng hoàn hảo giữa sự tươi mát và mịn màng. Lớp bọt nitro làm cho mỗi ngụm thêm phần đặc biệt, đầy lôi cuốn.',
                'Schweppes Soda Lon 320ml' => 'Schweppes Soda Lon 320ml là lựa chọn sảng khoái với hương vị soda tinh khiết. Đồ uống này rất lý tưởng để giải khát, hoặc kết hợp với các loại cocktail và đồ uống khác để tạo nên sự hòa quyện tuyệt hảo.',
                'Schweppes Tonic Lon 320ml' => 'Schweppes Tonic Lon 320ml mang đến hương vị tonic đặc trưng với độ đắng nhẹ vừa phải, thích hợp cho những ai yêu thích cảm giác mới lạ. Có thể thưởng thức riêng hoặc kết hợp với các loại rượu để tạo nên ly cocktail hoàn hảo.',
            ],
            'chicken' => [
                'Cánh gà nướng' => 'Cánh gà nướng là một món ăn hấp dẫn với lớp da vàng ruộm, giòn rụm sau khi được nướng chín tới. Từng chiếc cánh gà được ướp gia vị kỹ lưỡng, giúp thấm đều các hương vị vào sâu bên trong từng thớ thịt. Khi thưởng thức, bạn sẽ cảm nhận được lớp da giòn tan bên ngoài, hòa quyện với thịt gà mềm ngọt bên trong, mang đến một trải nghiệm ẩm thực vừa miệng lại cực kỳ lôi cuốn. Đây là món ăn lý tưởng để nhâm nhi khi tụ họp cùng bạn bè hay gia đình, đặc biệt khi kết hợp cùng một chút sốt cay nhẹ hay chấm kèm với tương ớt sẽ càng thêm hấp dẫn.',
                'Gà không xương sốt cay' => 'Gà không xương sốt cay là món ăn đậm chất "nóng bỏng", thách thức mọi tín đồ ẩm thực yêu thích vị cay nồng. Những miếng thịt gà mềm mại, không xương, được áo đều lớp sốt cay nồng và đậm đà, kích thích vị giác ngay từ miếng đầu tiên. Lớp sốt cay không chỉ tạo nên độ "bỏng rát" trên đầu lưỡi mà còn có vị chua ngọt tinh tế, làm dậy lên hương vị tổng thể của món ăn. Khi nhai, từng miếng thịt tan trong miệng, để lại hậu vị cay ngọt khó quên, khiến bạn muốn ăn thêm và không ngừng gắp. Đây là món ăn không thể thiếu trong thực đơn của những ai mê cảm giác cay nồng.',
                'Gà không xương mắm tỏi' => 'Gà không xương mắm tỏi là sự kết hợp tuyệt vời giữa hương vị truyền thống và nét hiện đại. Từng miếng thịt gà không xương được tẩm ướp cẩn thận với mắm tỏi thơm lừng, mang đến một vị mặn ngọt hài hòa và rất đặc trưng. Khi thưởng thức, bạn sẽ cảm nhận được lớp mắm tỏi thấm đều từng thớ thịt, hương tỏi phi thơm giòn khiến món ăn trở nên đặc biệt quyến rũ. Cắn vào miếng gà, hương vị bùng nổ ngay trong miệng với sự đậm đà và chút vị ngọt nhẹ từ mắm. Đây là một món ăn hoàn hảo cho bữa tối thịnh soạn hay các buổi tiệc nhỏ cùng bạn bè, đặc biệt là khi ăn kèm cơm nóng hay bánh mì.',
                'Cánh gà sốt cay' => 'Cánh gà sốt cay là món ăn không dành cho những ai sợ "nóng". Lớp cánh gà giòn rụm bên ngoài được nhúng ngập trong nước sốt cay đặc biệt, tạo nên hương vị lôi cuốn mà chỉ cần ngửi thôi đã đủ làm bụng reo lên. Từng miếng gà khi cắn vào, vị cay xé lưỡi sẽ lan tỏa ngay trên đầu lưỡi, nhưng sau đó là cảm giác bùi bùi, ngọt ngọt của thịt gà chín mềm. Nước sốt cay đặc sệt phủ đều lên từng chiếc cánh, mang lại một trải nghiệm vừa đau vừa thích thú cho những ai yêu thích ẩm thực cay nồng. Thưởng thức món này vào những ngày trời lạnh hay trong các buổi tối xem phim cùng bạn bè thì không gì sánh bằng.',
                'Gà phủ phô mai' => 'Gà phủ phô mai là một món ăn cực kỳ hấp dẫn và đầy "mỡ màng" đối với các tín đồ phô mai. Từng miếng gà được chiên giòn rụm, sau đó phủ lên lớp phô mai tan chảy vàng ươm, mang lại một hương vị béo ngậy đầy quyến rũ. Khi bạn cắn vào, lớp phô mai kéo sợi đầy hấp dẫn, kết hợp cùng thịt gà thơm lừng bên trong tạo nên một sự kết hợp hoàn hảo của vị ngọt, mặn và béo. Phô mai tan chảy phủ đều, hòa quyện vào từng thớ thịt gà làm tăng thêm độ ngon miệng và khiến món ăn trở nên đặc biệt lôi cuốn. Đây chắc chắn là món ăn hoàn hảo cho những ngày cần một chút "an ủi" tinh thần hay đơn giản là khi bạn muốn tận hưởng một món ăn béo ngậy đầy thú vị.',
                'Đùi gà chiên giòn' => 'Đùi gà chiên giòn mang đến một trải nghiệm ăn uống không thể cưỡng lại với lớp vỏ ngoài giòn rụm và phần thịt bên trong mềm mại, thấm đều gia vị. Mỗi miếng đùi gà đều được chiên vàng óng ánh, lớp da giòn tan trong miệng còn phần thịt thì mọng nước và ngọt tự nhiên. Khi ăn vào, bạn sẽ cảm nhận được vị giòn tan của lớp vỏ, kèm theo đó là sự đậm đà của gia vị đã được ướp kỹ lưỡng. Đây là món ăn hoàn hảo để nhâm nhi trong các buổi tiệc, làm món ăn nhẹ hoặc thậm chí là món chính trong bữa ăn của gia đình bạn. Đặc biệt, đùi gà chiên giòn khi kết hợp cùng các loại nước chấm như sốt cay, tương ớt hay sốt mayonnaise thì càng thêm phần hấp dẫn.',
                'Gà nướng mật ong' => 'Gà nướng mật ong mang đến một sự hòa quyện hoàn hảo giữa vị ngọt dịu của mật ong và vị mặn nhẹ từ các loại gia vị tẩm ướp. Lớp da gà được nướng chín tới, giòn giòn và bóng bẩy với màu vàng nâu hấp dẫn. Khi cắn vào, mật ong ngọt ngào thấm vào từng thớ thịt gà mềm mại, tạo nên hương vị độc đáo và khó cưỡng. Món ăn không chỉ bắt mắt mà còn đem lại sự ngon miệng ngay từ miếng đầu tiên, làm say lòng cả những thực khách khó tính nhất. Đây là lựa chọn hoàn hảo cho những buổi tiệc ngoài trời, bữa tối gia đình hay những dịp đặc biệt cần một món ăn ngon, dễ làm và đủ hấp dẫn để gây ấn tượng.',
            ],
            'combo' => [
                'Combo 2 Pizza + Pepsi - Ăn thả ga - Giá siêu rẻ' => 'Combo hoàn hảo dành cho những ngày tụ họp bạn bè hoặc gia đình. Chỉ cần gọi một lần là có ngay hai chiếc pizza cực ngon và một lon Pepsi mát lạnh, vừa ăn vừa uống, tha hồ tận hưởng mà không lo về giá. Pizza đa dạng vị, từ hải sản đến phô mai, kết hợp với Pepsi giúp tăng hương vị, khiến bữa ăn thêm phần hấp dẫn.',
                'Combo Sương Sương' => 'Combo "sương sương" nhưng chất lượng không sương đâu nha! Gồm các món ăn nhẹ nhưng siêu ngon, lý tưởng cho những lúc đói bụng nhẹ hoặc khi bạn muốn nhâm nhi chút gì đó trong giờ nghỉ. Món ăn phong phú, từ pizza mini đến khoai tây chiên, giúp bạn thỏa mãn cơn thèm một cách đầy tinh tế.',
                'Ăn Hết Menu Không Lo Mập Ú' => 'Không cần lo lắng về việc ăn nhiều sẽ tăng cân, combo này được thiết kế để vừa ngon miệng lại không quá nặng nề. Các món ăn đều được làm từ nguyên liệu tươi ngon và có hàm lượng calo hợp lý, phù hợp cho những ai muốn ăn uống thả ga nhưng vẫn giữ gìn vóc dáng.',
                'Dành Cho Người Ăn Kiêng' => 'Combo đặc biệt dành riêng cho những ai đang theo chế độ ăn kiêng. Các món ăn được lựa chọn kỹ lưỡng, giảm bớt dầu mỡ và đường, nhưng vẫn đảm bảo độ ngon không hề kém cạnh. Thực đơn bao gồm các loại salad tươi ngon, pizza ăn kiêng ít calo và nước ép tự nhiên, giúp bạn giữ dáng mà vẫn được ăn ngon.',
                'Ăn Một Mình Nhưng Phải Đủ Món' => 'Dành cho những "chiến binh ăn uống" muốn thưởng thức nhiều món mà không cần chia sẻ. Combo này bao gồm nhiều món ngon từ pizza, gà chiên, salad cho đến các loại nước uống, đảm bảo làm đầy dạ dày bạn mà không cảm thấy ngán. Hoàn hảo cho những buổi tối xem phim một mình.',
                'Pizza Slay' => 'Combo này là sự kết hợp hoàn hảo giữa các loại pizza "slay" chất lừ, được phủ đầy phô mai và topping đa dạng. Với những ai yêu thích pizza và muốn thử nhiều vị khác nhau, combo này là lựa chọn tuyệt vời. Bạn có thể thỏa sức ăn uống và tận hưởng các hương vị từ truyền thống đến sáng tạo.',
                'Combo Siêu To Khổng Lồ' => 'Combo dành cho những bữa tiệc đông người hoặc những ai muốn ăn uống "thả phanh". Gồm nhiều món ăn lớn với phần cực kỳ "siêu to khổng lồ", từ pizza, cánh gà, đến nước ngọt đầy ắp, đảm bảo no căng bụng. Chắc chắn là lựa chọn hoàn hảo cho những bữa tiệc tụ tập.',
                'Gia Đình Vui Vẻ - Cả Nhà Cùng Vui' => 'Combo lý tưởng cho bữa tối gia đình, với các món ăn phong phú và đủ khẩu phần cho mọi thành viên. Gồm pizza thơm ngon, salad bổ dưỡng, và nước uống mát lạnh, giúp cả nhà có một bữa ăn đầy ắp niềm vui. Chỉ cần gọi một lần, cả gia đình cùng ngồi lại và tận hưởng.',
                'Cặp Đôi Yêu Thương - Ăn Là Phải Có Đôi' => 'Dành riêng cho các cặp đôi muốn thưởng thức một bữa ăn lãng mạn nhưng vẫn đầy đủ chất. Combo này bao gồm hai phần pizza, một món phụ và hai loại nước uống, tạo nên một bữa ăn tuyệt vời cho hai người. Hãy cùng người thương tận hưởng những khoảnh khắc ăn uống vui vẻ nhé!',
                'Năng Lượng Ngập Tràn - Đầy Đủ Chất' => 'Nếu bạn cần một bữa ăn giàu năng lượng để "sạc pin" cho cả ngày dài, đây là combo hoàn hảo. Các món ăn đầy đủ chất dinh dưỡng, từ pizza với topping thịt đến salad tươi ngon và nước ép trái cây, giúp bạn nạp năng lượng tức thì và luôn trong trạng thái "sẵn sàng chiến đấu".',
                'Ăn Vặt Cuối Tuần - Nhâm Nhi Cả Ngày' => 'Cuối tuần là lúc để thư giãn và thưởng thức đồ ăn vặt, và combo này sẽ không làm bạn thất vọng. Với các món ăn nhẹ như khoai tây chiên, pizza mini, và cánh gà, bạn có thể thoải mái nhâm nhi cả ngày mà không lo thiếu món ngon. Combo lý tưởng để nhâm nhi bên tách trà hoặc cùng nhóm bạn chơi game.',
                'Mua 1 Tặng 1 - Tiết Kiệm Nhân Đôi' => 'Combo tiết kiệm "nhân đôi" giúp bạn vừa được ăn ngon lại vừa tiết kiệm. Chỉ cần mua một phần là bạn sẽ nhận ngay thêm một phần tương tự miễn phí. Đây là cơ hội vàng để chia sẻ cùng bạn bè hoặc gia đình mà không tốn thêm chi phí.',
            ]
        ];

        // Create Product
        $categories = Category::all();

        foreach ($categories as $category) {
            $products = $dataProduct[$category->slug] ?? [];

            foreach ($products as $productName => $description) {
                $price = rand(100000, 500000);

                // Create Product
                $createdProduct = Product::create([
                    'name' => $productName,
                    'slug' => Str::slug($productName),
                    'image' => Str::slug($productName) . '.jpeg',
                    'description' => $description,
                    'category_id' => $category->id,
                    'price' => $price,
                    'discount_price' => $price - rand(50000, 10000),
                    'quantity' => rand(10, 100),
                    'sku' => Str::random(10),
                    'status' => rand(1, 2),
                    'is_featured' => rand(0, 1),
                    'avg_rating' => rand(1, 5),
                    'total_rating' => rand(0, 100),
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);

                // Get Attribute Values
                $attributeValues = AttributeValue::all();

                foreach ($attributeValues as $attributeValue) {
                    $price = rand(10000, 50000);
                    ProductAttribute::create([
                        'product_id' => $createdProduct->id,
                        'attribute_value_id' => $attributeValue->id,
                        'price' => $price,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]);
                }
            }
        }
    }
}
